---
name: Docker Release

on:
  push:
    tags:
      - "v*"

jobs:
  docker:
    name: Docker Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build and push Docker base images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mcauto/todo-list-fastapi-base
          dockerfile: base.Dockerfile
          tag_with_ref: true
      - name: Build and push Docker app images
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: mcauto/todo-list-fastapi
          dockerfile: app.Dockerfile
          build_args: BASE_IMAGE=mcauto/todo-list-fastapi-base:latest
          tag_with_ref: true
